apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photo-uat-mmp
  annotations:
    argo.octopus.com/project: "photo"
    argo.octopus.com/environment: "uat"
    argo.octopus.com/tenant: "mmp"
    argo.octopus.com/image-replace-paths: "gitea:3000/admin/photo:{{ .Values.photo.image.tag }}"
spec:
  project: default
  source:
    repoURL: http://gitea:3000/admin/manufacturing-configs.git
    targetRevision: HEAD
    path: north-america/mmp/uat/photo
  destination:
    namespace: photo-uat-mmp
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true