{{- if .Values.imageCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
  labels:
    app: {{ include "data-pipeline.fullname" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  {{- $auth := printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc }}
  {{- $cfg := dict "auths" (dict .Values.imageCredentials.registry (dict "username" .Values.imageCredentials.username "password" .Values.imageCredentials.password "auth" $auth)) }}
  .dockerconfigjson: {{ $cfg | toJson | quote }}
{{- end }}
