{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-pipeline.serviceAccountName" . }}
  labels:
    {{- include "data-pipeline.labels" . | nindent 4 }}
{{- end }}