# providers.tf
terraform {
  required_version = ">= 1.0"

  required_providers {
    octopusdeploy = {
      source  = "OctopusDeploy/octopusdeploy"
      version = "~> 1.19"
    }
    gitea = {
      source  = "go-gitea/gitea"
      version = "~> 0.8"
    }
    argocd = {
      source  = "argoproj-labs/argocd"
      version = "~> 7.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    external = {
      source  = "hashicorp/external"
      version = "~> 2.3"
    }
  }
}

# Deliberately NO space_id here (kept per-resource instead, via
# var.octopus_space_id — defaults to "Spaces-1", the instance's built-in
# Default space; this configuration no longer creates its own dedicated
# space). A provider-level space_id would apply globally with no per-resource
# override, so setting it per-resource instead keeps this consistent with
# how the rest of this configuration is written.
provider "octopusdeploy" {
  address = var.octopus_server_url
  api_key = var.octopus_api_key
}

# Terraform runs on the host, so this talks to Gitea over its host-mapped
# port (localhost:3000) — content written *into* seeded files (repoURLs
# Argo CD itself will resolve) uses the in-cluster/in-network hostname
# "gitea:3000" instead, since that's resolved by pods inside KinD, not by
# Terraform itself. See terraform.tfvars (generated by the Vagrantfile) for
# these values.
provider "gitea" {
  base_url = var.gitea_url
  username = var.gitea_username
  password = var.gitea_password
}

# Argo CD tokens are minted per login, not baked into the image — unlike
# the Octopus API key and Gitea/Argo CD passwords, there's no fixed literal
# to just supply as a variable. Rather than push that token-minting step
# out to whatever's calling `terraform apply` (the Vagrantfile, or an
# Instruqt track_scripts/setup-track-image), this data source does it
# itself: port-forward to argocd-server, log in with the known "octopus"
# account password, mint a fresh token. Runs on every plan/apply — cheap,
# and Argo CD doesn't limit how many tokens an account can hold, so a
# stale one left behind by a previous run is harmless.
data "external" "argocd_token" {
  program = ["bash", "-c", <<-EOT
    set -euo pipefail
    export KUBECONFIG="${var.kubeconfig_path}"

    # Confirm Argo CD's own resources actually exist before even trying to
    # port-forward to them — a much clearer failure than "port never came
    # up" when the real problem is that Argo CD hasn't been installed onto
    # the cluster yet at all.
    RESOURCES_READY=0
    for i in $(seq 1 40); do
      if kubectl get namespace argocd >/dev/null 2>&1 \
          && [ "$(kubectl -n argocd get deployment argocd-server --no-headers 2>/dev/null | wc -l)" -gt 0 ]; then
        RESOURCES_READY=1
        break
      fi
      echo "  ...waiting for Argo CD resources to exist (attempt $i/40)" >&2
      sleep 15
    done
    if [ "$RESOURCES_READY" -ne 1 ]; then
      echo "Argo CD resources (namespace/argocd-server deployment) never appeared" >&2
      exit 1
    fi

    kubectl -n argocd port-forward svc/argocd-server 19443:443 >/tmp/argocd-tf-token-pf.log 2>&1 &
    PF_PID=$!
    trap 'kill "$PF_PID" >/dev/null 2>&1 || true' EXIT

    READY=0
    for i in $(seq 1 20); do
      if (exec 3<>/dev/tcp/127.0.0.1/19443) 2>/dev/null; then
        exec 3>&- 3<&- 2>/dev/null
        READY=1
        break
      fi
      echo "  ...waiting for the argocd-server port-forward (attempt $i/20)" >&2
      sleep 15
    done
    if [ "$READY" -ne 1 ]; then
      echo "Argo CD port-forward never came up: $(cat /tmp/argocd-tf-token-pf.log)" >&2
      exit 1
    fi

    # A retry here too: the port answering doesn't guarantee argocd-server
    # has finished its own internal startup (redis connection, initial
    # sync) the instant it starts accepting TCP connections.
    TOKEN=""
    for i in $(seq 1 10); do
      if argocd login localhost:19443 --username "${var.argocd_username}" --password "${var.argocd_password}" --insecure --plaintext >/dev/null 2>/tmp/argocd-tf-login.log; then
        TOKEN=$(argocd account generate-token --account "${var.argocd_username}" --insecure --plaintext 2>/tmp/argocd-tf-token-gen.log || true)
        [ -n "$TOKEN" ] && break
      fi
      echo "  ...waiting for argocd login to succeed (attempt $i/10)" >&2
      sleep 15
    done
    if [ -z "$TOKEN" ]; then
      echo "Could not generate an Argo CD token for the ${var.argocd_username} account" >&2
      echo "Last login attempt: $(cat /tmp/argocd-tf-login.log 2>/dev/null)" >&2
      echo "Last token-gen attempt: $(cat /tmp/argocd-tf-token-gen.log 2>/dev/null)" >&2
      exit 1
    fi

    jq -n --arg token "$TOKEN" '{"token": $token}'
  EOT
  ]
}

# Same host-vs-in-cluster distinction as Gitea above: server_addr here is
# the host-mapped NodePort Terraform itself talks to for its own resource
# operations (separate from the port-forward the data source above uses
# just to mint the token).
provider "argocd" {
  server_addr = var.argocd_server_addr
  auth_token  = data.external.argocd_token.result.token
  insecure    = var.argocd_insecure
  plain_text  = var.argocd_plain_text
}