apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: probe-sqa-fab-10n
  annotations:
    argo.octopus.com/project: "probe"
    argo.octopus.com/environment: "sqa"
    argo.octopus.com/tenant: "fab-10n"
    argo.octopus.com/image-replace-paths: "gitea:3000/admin/probe:{{ .Values.probe.image.tag }}"
spec:
  project: default
  source:
    repoURL: http://gitea:3000/admin/manufacturing-configs.git
    targetRevision: HEAD
    path: north-america/fab-10n/sqa/probe
  destination:
    namespace: probe-sqa-fab-10n
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
