apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: probe-production-fab-15
  annotations:
    argo.octopus.com/project: "probe"
    argo.octopus.com/environment: "production"
    argo.octopus.com/tenant: "fab-15"
    argo.octopus.com/image-replace-paths: "gitea:3000/admin/probe:{{ .Values.probe.image.tag }}"
spec:
  project: default
  source:
    repoURL: http://gitea:3000/admin/manufacturing-configs.git
    targetRevision: HEAD
    path: asia/fab-15/production/probe
  destination:
    namespace: probe-production-fab-15
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
