apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: probe
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://gitea:3000/admin/manufacturing-configs.git
        revision: HEAD
        files:
          - path: "*/*/*/probe/values.yaml"
  template:
    metadata:
      name: 'probe-{{ index .path.segments 2 }}-{{ index .path.segments 1 }}'
    spec:
      project: default
      source:
        repoURL: http://gitea:3000/admin/manufacturing-configs.git
        targetRevision: HEAD
        path: '{{ index .path.segments 0 }}/{{ index .path.segments 1 }}/{{ index .path.segments 2 }}/probe'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'probe-{{ index .path.segments 2 }}-{{ index .path.segments 1 }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=false
          - CreateNamespace=true
