apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
spec:
  template:
    spec:
      containers:
      - name: probe
        env:
        - name: BG_COLOR
          value: "#27ae60"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi